// <auto-generated />
using System;
using Infrastructure.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20230428143831_add_missing_relation")]
    partial class add_missing_relation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.ArchivalRental", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CopyHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CopyInventoryNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PenaltyCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProfileHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfileLibraryCardNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CopyHistoryId");

                    b.HasIndex("CopyInventoryNumber");

                    b.HasIndex("ProfileHistoryId");

                    b.HasIndex("ProfileLibraryCardNumber");

                    b.ToTable("ArchivalRentals");
                });

            modelBuilder.Entity("Domain.Entities.ArchivalReservation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CollectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CopyHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CopyInventoryNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfileLibraryCardNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CopyHistoryId");

                    b.HasIndex("CopyInventoryNumber");

                    b.HasIndex("ProfileHistoryId");

                    b.HasIndex("ProfileLibraryCardNumber");

                    b.ToTable("ArchivalReservations");
                });

            modelBuilder.Entity("Domain.Entities.Copy", b =>
                {
                    b.Property<string>("InventoryNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CopyHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentRentalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrentReservationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LibraryId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("InventoryNumber");

                    b.HasIndex("CopyHistoryId");

                    b.HasIndex("CurrentRentalId")
                        .IsUnique()
                        .HasFilter("[CurrentRentalId] IS NOT NULL");

                    b.HasIndex("CurrentReservationId")
                        .IsUnique()
                        .HasFilter("[CurrentReservationId] IS NOT NULL");

                    b.HasIndex("ItemId");

                    b.HasIndex("LibraryId");

                    b.ToTable("Copies");
                });

            modelBuilder.Entity("Domain.Entities.CopyHistory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("CopyHistories");
                });

            modelBuilder.Entity("Domain.Entities.Item", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Authors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormOfPublication")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("YearOfPublication")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Domain.Entities.Library", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPhotocopier")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrinter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScanner")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfComputerStations")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Domain.Entities.Profile", b =>
                {
                    b.Property<string>("LibraryCardNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileHistoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LibraryCardNumber");

                    b.HasIndex("ProfileHistoryId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("Domain.Entities.ProfileHistory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("ProfilesHistories");
                });

            modelBuilder.Entity("Domain.Entities.Rental", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PenaltyCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProfileLibraryCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileLibraryCardNumber");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileLibraryCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileLibraryCardNumber");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Domain.Entities.ArchivalRental", b =>
                {
                    b.HasOne("Domain.Entities.CopyHistory", "CopyHistory")
                        .WithMany("ArchivalRentals")
                        .HasForeignKey("CopyHistoryId");

                    b.HasOne("Domain.Entities.Copy", "Copy")
                        .WithMany()
                        .HasForeignKey("CopyInventoryNumber");

                    b.HasOne("Domain.Entities.ProfileHistory", "ProfileHistory")
                        .WithMany("ArchivalRentals")
                        .HasForeignKey("ProfileHistoryId");

                    b.HasOne("Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileLibraryCardNumber");

                    b.Navigation("Copy");

                    b.Navigation("CopyHistory");

                    b.Navigation("Profile");

                    b.Navigation("ProfileHistory");
                });

            modelBuilder.Entity("Domain.Entities.ArchivalReservation", b =>
                {
                    b.HasOne("Domain.Entities.CopyHistory", "CopyHistory")
                        .WithMany("ArchivalReservations")
                        .HasForeignKey("CopyHistoryId");

                    b.HasOne("Domain.Entities.Copy", "Copy")
                        .WithMany()
                        .HasForeignKey("CopyInventoryNumber");

                    b.HasOne("Domain.Entities.ProfileHistory", "ProfileHistory")
                        .WithMany("ArchivalReservations")
                        .HasForeignKey("ProfileHistoryId");

                    b.HasOne("Domain.Entities.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileLibraryCardNumber");

                    b.Navigation("Copy");

                    b.Navigation("CopyHistory");

                    b.Navigation("Profile");

                    b.Navigation("ProfileHistory");
                });

            modelBuilder.Entity("Domain.Entities.Copy", b =>
                {
                    b.HasOne("Domain.Entities.CopyHistory", "CopyHistory")
                        .WithMany()
                        .HasForeignKey("CopyHistoryId");

                    b.HasOne("Domain.Entities.Rental", "CurrentRental")
                        .WithOne("Copy")
                        .HasForeignKey("Domain.Entities.Copy", "CurrentRentalId");

                    b.HasOne("Domain.Entities.Reservation", "CurrentReservation")
                        .WithOne("Copy")
                        .HasForeignKey("Domain.Entities.Copy", "CurrentReservationId");

                    b.HasOne("Domain.Entities.Item", "Item")
                        .WithMany("Copies")
                        .HasForeignKey("ItemId");

                    b.HasOne("Domain.Entities.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId");

                    b.Navigation("CopyHistory");

                    b.Navigation("CurrentRental");

                    b.Navigation("CurrentReservation");

                    b.Navigation("Item");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Domain.Entities.Profile", b =>
                {
                    b.HasOne("Domain.Entities.ProfileHistory", "ProfileHistory")
                        .WithMany()
                        .HasForeignKey("ProfileHistoryId");

                    b.Navigation("ProfileHistory");
                });

            modelBuilder.Entity("Domain.Entities.Rental", b =>
                {
                    b.HasOne("Domain.Entities.Profile", "Profile")
                        .WithMany("CurrentRentals")
                        .HasForeignKey("ProfileLibraryCardNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.HasOne("Domain.Entities.Profile", "Profile")
                        .WithMany("CurrrentReservations")
                        .HasForeignKey("ProfileLibraryCardNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Domain.Entities.CopyHistory", b =>
                {
                    b.Navigation("ArchivalRentals");

                    b.Navigation("ArchivalReservations");
                });

            modelBuilder.Entity("Domain.Entities.Item", b =>
                {
                    b.Navigation("Copies");
                });

            modelBuilder.Entity("Domain.Entities.Profile", b =>
                {
                    b.Navigation("CurrentRentals");

                    b.Navigation("CurrrentReservations");
                });

            modelBuilder.Entity("Domain.Entities.ProfileHistory", b =>
                {
                    b.Navigation("ArchivalRentals");

                    b.Navigation("ArchivalReservations");
                });

            modelBuilder.Entity("Domain.Entities.Rental", b =>
                {
                    b.Navigation("Copy")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Copy")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
